"""PDF download + QR verification endpoints."""
from __future__ import annotations

from fastapi import APIRouter, Body, Request
from fastapi.responses import Response

from app.services import pdf

router = APIRouter(prefix="/api")


@router.post("/pdf")
def make_pdf(request: Request, payload: dict = Body(...)):
    base = str(request.base_url).rstrip("/")
    pdf_bytes = pdf.build_pdf(payload, verify_url_base=base)
    name = (payload.get("patient", {}).get("name") or "report").replace(" ", "_")
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="AudioSense_{name}.pdf"'},
    )


@router.get("/verify/{h}")
def verify(h: str):
    entry = pdf.lookup_hash(h)
    if entry:
        return {"valid": True, "hash": h, **entry,
                "message": "This report was generated by AudioSense AI and its "
                           "contents match the recorded analysis."}
    return {"valid": False, "hash": h,
            "message": "Unknown hash — this report was not generated by this "
                       "AudioSense AI instance."}
