"""Otoacoustic emissions — the cochlea's own echo.

Distortion-product OAEs are generated by outer hair cells and measured
without any voluntary response from the patient. Two properties make them
the most valuable test in this battery:

1. OUTER HAIR CELLS DIE BEFORE THRESHOLDS MOVE. Emissions disappear while
   the audiogram still reads normal, so absent OAEs with normal thresholds
   is *pre-clinical* cochlear damage — noise injury caught while it is
   still preventable. This is the difference between screening for damage
   already done and screening for damage about to happen.

2. THEY CANNOT BE FAKED. Present emissions in an ear whose thresholds are
   reported as poor means either exaggeration (non-organic loss) or a
   lesion beyond the cochlea (auditory neuropathy) — the audiogram is not
   telling the truth on its own.

A DPOAE is conventionally judged present when the emission exceeds the
noise floor by >= 6 dB, at an absolute level above about -5 dB SPL.
"""
from __future__ import annotations

from typing import Dict, List, Optional

OAE_FREQS = [1000, 2000, 4000, 8000]
#: Signal-to-noise ratio (dB) at which an emission counts as present.
SNR_PRESENT_DB = 6.0
#: Thresholds above this rarely produce measurable emissions, so an absent
#: result there carries no extra information.
OAE_CEILING_DB_HL = 50.0


def classify_oae(points: List[dict]) -> Optional[dict]:
    """Present / absent per frequency from DPOAE amplitude and noise floor.

    ``points``: [{"freq": Hz, "amplitude": dB SPL, "noise_floor": dB SPL}]
    """
    if not points:
        return None
    results = []
    for p in points:
        freq = int(p["freq"] if isinstance(p, dict) else p.freq)
        amp = float(p["amplitude"] if isinstance(p, dict) else p.amplitude)
        nf = float(p["noise_floor"] if isinstance(p, dict) else p.noise_floor)
        snr = round(amp - nf, 1)
        results.append({
            "freq": freq, "amplitude": amp, "noise_floor": nf, "snr": snr,
            "present": snr >= SNR_PRESENT_DB,
        })
    results.sort(key=lambda r: r["freq"])
    present = [r["freq"] for r in results if r["present"]]
    absent = [r["freq"] for r in results if not r["present"]]
    return {
        "points": results,
        "present_freqs": present,
        "absent_freqs": absent,
        "all_present": not absent,
        "all_absent": not present,
        "criterion": f"emission ≥ {SNR_PRESENT_DB:g} dB above the noise floor",
    }


def oae_audiogram_agreement(
    oae: Optional[dict],
    ac_numeric: Dict[int, Optional[float]],
) -> List[dict]:
    """Compare emissions against thresholds frequency by frequency.

    Returns the clinically meaningful mismatches — the whole point of
    running OAEs alongside pure tones.
    """
    if not oae:
        return []
    findings = []
    for r in oae["points"]:
        thr = ac_numeric.get(r["freq"])
        if thr is None:
            continue
        if not r["present"] and thr <= 20:
            findings.append({
                "freq": r["freq"], "kind": "preclinical_damage",
                "detail": (
                    f"{r['freq']} Hz: emissions absent (SNR {r['snr']:g} dB) despite a "
                    f"normal threshold of {thr:g} dB HL — outer hair cell damage is "
                    "present before the audiogram has moved."
                ),
            })
        elif r["present"] and thr > OAE_CEILING_DB_HL:
            findings.append({
                "freq": r["freq"], "kind": "oae_threshold_mismatch",
                "detail": (
                    f"{r['freq']} Hz: emissions present although the threshold is "
                    f"{thr:g} dB HL. A working cochlea with that threshold points to "
                    "exaggerated responses or a lesion beyond the cochlea."
                ),
            })
    return findings


def analyze_oae(ear, ac_numeric: Dict[int, Optional[float]]) -> Optional[dict]:
    """Full OAE review for one ear (EarData)."""
    oae = classify_oae(ear.oae or [])
    if not oae:
        return None
    mismatches = oae_audiogram_agreement(oae, ac_numeric)
    return {
        **oae,
        "mismatches": mismatches,
        "preclinical_damage": [m for m in mismatches if m["kind"] == "preclinical_damage"],
        "unexplained_emissions": [
            m for m in mismatches if m["kind"] == "oae_threshold_mismatch"
        ],
    }
